In [2]:
import numpy as np

In [6]:
# 1) Create a numpy array with numpy.array module and with a data type integer and float

In [16]:
l = [1,2,3,4,5,6,7,8,9]

In [22]:
arr = np.array(l, float)

In [24]:
arr

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [14]:
#2) Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
#   Also, print the shape and dimensions of the numpy arrays created above.

In [36]:
arr0 = np.array(2)
print(arr0.shape)
print(arr0.ndim)
print(arr0)

()
0
2


In [38]:
arr1 = np.array([1,2,3,4])
print(arr1.shape)
print(arr1.ndim)
print(arr1)

(4,)
1
[1 2 3 4]


In [42]:
arr2 = np.array([[1,2,3,4], [6,5,4,3]])
print(arr2.shape)
print(arr2.ndim)
print(arr2)

(2, 4)
2
[[1 2 3 4]
 [6 5 4 3]]


In [44]:
arr3 = np.array([[[1,2,3,4], [6,5,4,3]],[[1,2,3,4], [6,5,4,3]],[[1,2,3,4], [6,5,4,3]]])
print(arr3.shape)
print(arr3.ndim)
print(arr3)

(3, 2, 4)
3
[[[1 2 3 4]
  [6 5 4 3]]

 [[1 2 3 4]
  [6 5 4 3]]

 [[1 2 3 4]
  [6 5 4 3]]]


In [81]:
arr4 = np.array([[[[1,2,3,4], 
                   [6,5,4,3]],
                  [[1,2,3,4], 
                   [6,5,4,3]],
                  [[1,2,3,4], 
                   [6,5,4,3]]],
                 [[[1,2,3,4], 
                   [6,5,4,3]],
                  [[1,2,3,4], 
                   [6,5,4,3]],
                  [[1,2,3,4], 
                   [6,5,4,3]]]])
print(arr4.shape)
print(arr4.ndim)
print(arr4)

(2, 3, 2, 4)
4
[[[[1 2 3 4]
   [6 5 4 3]]

  [[1 2 3 4]
   [6 5 4 3]]

  [[1 2 3 4]
   [6 5 4 3]]]


 [[[1 2 3 4]
   [6 5 4 3]]

  [[1 2 3 4]
   [6 5 4 3]]

  [[1 2 3 4]
   [6 5 4 3]]]]


In [50]:
#3) Create a 2x3, 3x3, and 4x4 identity matrix using numpy.
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [52]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [58]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#shift diagonal
np.eye(2,3,1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [64]:
np.eye(2,3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [66]:
np.eye(2,3,k=2)

array([[0., 0., 1.],
       [0., 0., 0.]])

In [75]:
np.eye(3,3,k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [83]:
#4) Create a numpy array with shape 2x5 and all the elements should be zero.

In [87]:
#6) Create a numpy array with random integers in the range 0-100, and the sample size
# should be 25.


In [89]:
np.random.randint(0,101,25)

array([97, 79, 99, 34, 45, 76, 76,  9, 35, 51, 74, 95, 84, 54,  3, 96, 27,
       83, 95, 37, 46, 68, 22, 46, 22])

In [92]:
#7) 

In [95]:
#8) Create a numpy array in the shape 2x3 with random integers in the range 0-100.
# Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [103]:
a1 = np.random.randint(0,101,6)
print(a1)
a2 = a1.reshape(3,2)
print(a2)
a3 = a2.reshape(2,3)
print(a3)

[90 42 44 74 64 39]
[[90 42]
 [44 74]
 [64 39]]
[[90 42 44]
 [74 64 39]]


In [105]:
a2 = np.random.randint(0,101, size=(2,3))
print(a2)
a3 = a2.reshape(3,2)
print(a3)

[[69 28  6]
 [28 75 77]]
[[69 28]
 [ 6 28]
 [75 77]]


In [110]:
#9) Create a random array, with the range 0-1000, with a size 50 and 
# step 2. 
#    Perform the following operations on the same. a. Print the first ten elements of the array.
# b. Print the last ten elements of the array
# c. Print the elements from the indexes 10-25
# d. Print the element at the index 22
# e. Print the array using negative indexing.
# f.Print the last ten elements of the array, using negative indexing.

In [173]:
# 10) Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
#  a. Insert the element 6 at the end of the array.
#  b. Insert the element 10 at the beginning of the array.
#  c. Insert the element 30, before 4.
#  d. Update the element 5 as 50.
#  e. Delete the element 50 in the updated array.
#  f. Create a function to search for the element 30.
#  g. Sort the array in ascending order

In [155]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [157]:
arr2 = np.append(arr, 6)
print(arr2)

[1 2 3 4 5 6]


In [159]:
arr3 = np.insert(arr2, 0, 10)
print(arr3)

[10  1  2  3  4  5  6]


In [161]:
arr4 = np.insert(arr3, 4, 30)
print(arr4)

[10  1  2  3 30  4  5  6]


In [163]:
arr4[6]=50
print(arr4)

[10  1  2  3 30  4 50  6]


In [171]:
arr5 = np.delete(arr4, 6)
print(arr5)

[10  1  2  3 30  4  6]


# enumerate

In [175]:
fruits = ['apple', 'banana', 'orange']
for i,v in enumerate(fruits):
    print(i, v)

0 apple
1 banana
2 orange


In [178]:
fruits = ['apple', 'banana', 'orange']
for i,v in enumerate(fruits, start=1):
    print(i, v)

1 apple
2 banana
3 orange


In [184]:
scores = np.array([65, 70, 75, 80, 85, 90, 95])
# normalize the score to a 0 - 1 scale using formula 
# normalize = (x-min) / (max- min)

In [186]:
score1 = (scores - min(scores)) / (max(scores) - min(scores))
print(score1)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [188]:
score2 = (scores - scores.min()) / (scores.max() - scores.min())
print(score2)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [196]:
person_a = np.array([1200, 1100, 1300, 1250, 1400, 1350])
person_b = np.array([1000, 1150, 1200, 1100, 1250, 1300])
# find out in which month person a spent more than person b

for i in range(len(person_a)):
    if person_a[i]>person_b[i]:
        print(f'month {i+1}')

month 1
month 3
month 4
month 5
month 6


In [202]:
result = person_a > person_b
months = np.where(result)[0]+1
print(months)

[1 3 4 5 6]


In [210]:
result = person_a > person_b
months = np.where(result)[0]+1
print(months)

[1 3 4 5 6]


In [230]:
scores = np.array([77, 55, 76, 89, 67, 44, 23])
# find the mean , median ,stdev, highest
print(np.mean(scores))
print(np.median(scores))
print(np.std(scores))
print(np.max(scores))

61.57142857142857
67.0
20.934299557405396
89
