# Data Manipulation

- It is process of converting the data into a meaningful information that can be 
easily understand or processed as per the requirement 

- collecting the data 
- data manipulation is done with the help of python code 
- organizing the data into proper format


Problem 
- Duplicates 
- Missing values
- Incorrect format - dd/mm/yy - yy/dd/mm 
- Different units - F --- C , km --- m 
- Unwanted columns - S.No

# various libraries in python

- NumPy - Array 
- Pandas - Series and DataFrame 
- Matplotlib - Visualization 
- Seaborn - Visualization 
- Scipy - Stats

# NumPy

- Numerical Python 
- It is n dimensional Array
- Array is a rectangular matrix which consists of rows and columns 
- It is an open source library 
- it is free available 
- It consist of various inbuilt powerfull functions
- It is used for data generation and manipulation 
- We cannot change the index in NumPy 
- it consist of same data type

In [7]:
a = [10,20.5,6+5j, "python", True]
print(a)
print(type(a))

[10, 20.5, (6+5j), 'python', True]
<class 'list'>


In [9]:
import numpy as np 
a = np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [13]:
a = np.array([10,20,30.5,40,50])
print(a)
print(type(a))

[10.  20.  30.5 40.  50. ]
<class 'numpy.ndarray'>


In [15]:
a = np.array([10,20,30.5,'40',50])
print(a)
print(type(a))

['10' '20' '30.5' '40' '50']
<class 'numpy.ndarray'>


# Data Generation

In [18]:
a = np.array([0,0,0,0,0])
print(a)

[0 0 0 0 0]


In [20]:
# zeros 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.zeros((5,6))
print(a)
print(type(a))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [22]:
# ones 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6))
print(a)
print(type(a))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [24]:
# twos 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6))* 2
print(a)
print(type(a))

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
<class 'numpy.ndarray'>


In [26]:
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6)) + 54
print(a)
print(type(a))

[[55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]]
<class 'numpy.ndarray'>


In [28]:
# full 

# 5 - rows, 6 - column, 7 - number
# by default the data will be in form of float
a = np.full((5,6), 7)
print(a)
print(type(a))


[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
<class 'numpy.ndarray'>


In [30]:
# full 

# 5 - rows, 6 - column, 7.3 - number
# by default the data will be in form of float
a = np.full((5,6), 7.3)
print(a)
print(type(a))

[[7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]]
<class 'numpy.ndarray'>


In [33]:
# linspace - equal spacing 
# 0 - start, 20 - end point , 11 - no of point 
# start and end point are included

a = np.linspace(0,20,10)
print(a)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [35]:
a = np.linspace(0,20,25)
print(a)

[ 0.          0.83333333  1.66666667  2.5         3.33333333  4.16666667
  5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.         10.83333333 11.66666667 12.5        13.33333333 14.16666667
 15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


In [37]:
# arange 
# 0 - start, 20 - end , 3 - step size 
# end is not included 

a = np.arange(0,20,3)
print(a)

[ 0  3  6  9 12 15 18]


In [39]:
a = np.arange(0,20,5)
print(a)

[ 0  5 10 15]


In [65]:
# random 
# values will always between 0 and 1 
# 1 - random - module 2- random - function
# 40 - no. of points

a = np.random.random(3)
print(a)

[0.17269126 0.84542699 0.78054234]


In [57]:
# np.random.random() takes in a tuple as the size of the array.

a = np.random.random((3,4))
print(a)

[[0.3802721  0.72086093 0.20257725 0.69222002]
 [0.11882011 0.5223155  0.48535352 0.18765474]
 [0.29248779 0.78884771 0.81904642 0.11365376]]


In [63]:
# np.random.rand() takes in comma-separated integers as the size of the array.

a = np.random.rand(5)
print(a)

[0.83142696 0.09455942 0.41478771 0.31142466 0.26373533]


In [67]:
# np.random.rand() takes in comma-separated integers as the size of the array.

a = np.random.rand(2,3)
print(a)

[[0.61277509 0.44270198 0.5868947 ]
 [0.73077331 0.11391313 0.3054405 ]]


In [69]:
# randint
# 0 - start, 40 - end 

a = np.random.randint(0,40)
print(a)

36


In [79]:
# converting integer into float 

a = np.arange(24, dtype = float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


# Array Inspection

In [82]:
a = np.array(20)
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

20
<class 'numpy.ndarray'>
1
0
()


In [119]:
a = np.array([20,10,30,40,50])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[20 10 30 40 50]
<class 'numpy.ndarray'>
5
1
(5,)


In [121]:
a = np.array([20,10,30,40,50])
print(a)
print(type(a))
print(a.size) # count of elements present in the array
print(a.ndim) # dimension of the array
print(a.shape) # will give you the shape of the array

[20 10 30 40 50]
<class 'numpy.ndarray'>
5
1
(5,)


In [86]:
a = np.array([[20,10,30],
              [40,50,60]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[20 10 30]
 [40 50 60]]
<class 'numpy.ndarray'>
6
2
(2, 3)


In [88]:
a = np.array([[20,10,30,50],
              [40,50,60,70],
              [90,80,70,90]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[20 10 30 50]
 [40 50 60 70]
 [90 80 70 90]]
<class 'numpy.ndarray'>
12
2
(3, 4)


In [90]:
a = np.array([[[20,10,30,50],
              [40,50,60,70],
              [90,80,70,90]]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]]
<class 'numpy.ndarray'>
12
3
(1, 3, 4)


In [92]:
a = np.array([
              [[20,10,30,50],[40,50,60,70],[90,80,70,90]],
              [[20,10,30,50],[40,50,60,70],[90,80,70,90]]
             ])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]

 [[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]]
<class 'numpy.ndarray'>
24
3
(2, 3, 4)


# Comparision of Array

In [96]:
# element wise comparision

a = [1,2,3]
b = [1,3,4]
np.equal(a,b)

array([ True, False, False])

In [98]:
a = [1,2,3]
b = [1,2,3]
np.equal(a,b)

array([ True,  True,  True])

In [100]:
# array wise comparision

a = [1,2,3]
b = [1,3,4]
np.array_equal(a,b)

False

In [102]:
a = [1,2,3]
b = [1,2,3]
np.array_equal(a,b)

True

# Array Mathematics

In [78]:
a = [1,2,3,4,5]
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

1
5
3.0
3.0
1.4142135623730951


In [79]:
np.sqrt(100)

10.0

In [80]:
np.sin(10)

-0.5440211108893699

In [81]:
np.cos(10)

-0.8390715290764524

In [82]:
np.tan(10)

0.6483608274590867

In [83]:
np.log(10)

2.302585092994046

In [84]:
np.sum([10,20])

30

In [85]:
np.sum([10,20,30,40])

100

In [86]:
np.subtract(10,20)

-10

In [88]:
np.multiply(10,20)

200

In [89]:
np.divide(10,20)

0.5

In [90]:
np.pi

3.141592653589793

In [92]:
a = np.sum([[10,20], [20,50]])
a

100

In [96]:
# column wise summation
a = np.sum([[10,20], 
            [10,50]], axis = 0 )
a

array([20, 70])

In [95]:
# row wise summation
a = np.sum([[10,20], 
            [10,40]], axis = 1 )
a

array([30, 50])

In [102]:
# reshape 

a = np.arange(24)
print(a)
print(np.ndim(a))
print()

b = a.reshape(6,4)
print(b)
print(np.ndim(b))
print()

c = a.reshape(2,3,4)
print(c)
print(np.ndim(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


# indexing and slicing

In [105]:
# 1d
# indexing
a = np.array([10,20,30,40,50])
print(a)
# 10
a[0]

[10 20 30 40 50]


10

In [106]:
# 30 
a[2]

30

In [107]:
a[4]

50

In [108]:
a[-1]

50

In [110]:
# slicing
a = np.array([10,20,30,40,50])
# [10,20]
# a[start:end+1:step]
a[0:2:1]

array([10, 20])

In [111]:
a = np.array([10,20,30,40,50])
# [30,40]
a[2:4:1]

array([30, 40])

In [112]:
a = np.array([10,20,30,40,50])
# [20,40]
a[1:4:2]

array([20, 40])

In [113]:
# 2d
# indexing
a = np.array([[10,20,30],
              [40,50,60]])

# a[rows,column]
# 10
a[0,0]

10

In [114]:
# 50
a[1,1]

50

In [116]:
# 30
a[0,2]

30

In [117]:
# 3d
# indexing
a = np.array([[[10,20,30],
              [40,50,60],
              [90,80,70]]])

# a[array,rows,column]
# 10 
a[0,0,0]

10

In [118]:
a = np.array([[[10,20,30],
              [40,50,60],
              [90,80,70]]])
# 60
a[0,1,2]

60

In [119]:
# 70
a[0,2,2]

70

In [120]:
# 2d
# slicing
a = np.array([[10,20,30],
              [40,50,60]])

#[[10,20]]

# a[rstart:rend+1:rstep, cstart:cend+1:cstep]
a[0:1:1,0:2:1]



array([[10, 20]])

In [121]:
a = np.array([[10,20,30],
              [40,50,60]])

# [[50,60]]
a[1:2:1,1:3:1]

array([[50, 60]])

In [124]:
# 3d
a = np.array([[[10,20,30],
              [40,50,60]]])
# [[[50,60]]]

a[0:1:1, 1:2:1,1:3:1]

array([[[50, 60]]])

In [148]:
# list = []

# np.array(list)
# np.ones((rows, columns))
# np.zeros((rows, columns))
# np.full((rows, columns), number)

# np.linspace(start, end+1, number_of_points)
# np.arange(start, end+1, space_between_numbers)

# np.random.random(number_of_elements)                 #for 1-D array
# np.random.random((rows, column))                     #for 2-D array
# np.random.rand(rows, column)                         #for 1-D array
# np.random.randint(start, end)                        #for 2-D array

# np.equal(arr1, arr2)                                 #element-by-element comparison, returns an array of true/false
# np.array_equal(arr1, arr2)                           #array as a whole comparison, returns either true or false

# np.sum(array)                                        #sum of all the elements of an array
# np.sum(array,axis=0)                                 #sum of all elements from 1st axis
# np.sum(array,axis=1)                                 #sum of all elements from 2nd axis
# np.sum([arr1, arr2])

# np.subtract(num1, num2)
# np.subtract([arr1, arr2])

# np.multiply(num1, num2)
# np.multiply([arr1, arr2])

# np.divide(num1, num2)
# np.divide([arr1, arr2])

# np.sqrt(num)
# np.pi
# np.min(array)
# np.max(array)
# np.mean(array)
# np.median(array)
# np.std(array)

# np.sin(num)
# np.sin(array)

# np.cos(num)
# np.cos(array)

# np.tan(num)
# np.tan(array)

# np.log(num)
# np.log(array)

# np.exp(num)
# np.exp(array)

# np.corrcoef(array)

# np.size(array)
# array.size

# np.ndim(array)
# array.size

# np.shape(array)
# array.shape

# array.reshape(num_of_rows, num_of_columns)           #shows the changed shape but doesn't change the original shape.
# array.resize(num_of_rows, num_of_columns)            #changes the original shape of array

# np.concatenate((arr1, arr2))
# np.hstack((arr1, arr2))
# np.vstack((arr1, arr2))
# np.column_stack((arr1, arr2))                        #Transpose of vstack

# np.hsplit(array,2)                                   #split into 2 horizontal parts
# np.vsplit(array,3)                                   #split into 3 vertical parts

# **Handson**

In [125]:
# create an array with the help of list having values as float
a_1 = np.array([1.01, 2.8, 88.99, 21.88])
print(a_1)

[ 1.01  2.8  88.99 21.88]


In [126]:
# create an array with the help of zeros with 5 rows and 2 columns 
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [127]:
# create an array with the help of full with values as 33 
c = np.full([5,2],33)
print(c)

[[33 33]
 [33 33]
 [33 33]
 [33 33]
 [33 33]]


In [128]:
# create an array with the help of ones with 9 rows and 3 columns 
a=np.ones((9,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [129]:
# create an array with the help of linspace with equal spacing of 2 
np.linspace(0,20, 11)


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [130]:
# create an array with the help of arange with step size as 3 
a=np.arange(0,30,3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27]


In [131]:
# create an array with the help of random in which values lie between 10 and 11
a_arange = np.arange(0, 10, 3)
a_arange


array([0, 3, 6, 9])

In [132]:
# create an array with the help of random int between 10 and 100
np.random.randint(10, 100)


30

In [138]:
# create a 3d array and convert it into 2d and than into 1 d 
a_3d = np.random.randint(10, 100, size=(2, 3, 4))
print(a_3d)
print()
a_2d = a_3d.reshape((8, 3))
print(a_2d)
print()
a_1d = a_2d.reshape(1, 24)
print(a_1d)

[[[99 69 14 57]
  [80 10 84 34]
  [37 33 52 58]]

 [[98 92 52 33]
  [42 54 48 99]
  [53 47 35 81]]]

[[99 69 14]
 [57 80 10]
 [84 34 37]
 [33 52 58]
 [98 92 52]
 [33 42 54]
 [48 99 53]
 [47 35 81]]

[[99 69 14 57 80 10 84 34 37 33 52 58 98 92 52 33 42 54 48 99 53 47 35 81]]
