# ** numpy - Data Manipulation - HandsOn**

In [43]:
import numpy as np 

In [7]:
# create an array with the help of list having values as float

In [15]:
a1 = np.array([1,2,3,4,5,6], float)

In [17]:
print(a1)

[1. 2. 3. 4. 5. 6.]


In [ ]:
# create an array with the help of zeros with 5 rows and 2 columns

In [24]:
a2 = np.zeros((5,2))

In [26]:
print(a2)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# create an array with the help of full with values as 33 

In [33]:
a3 = np.full((5,7), 33)

In [35]:
print(a3)

[[33 33 33 33 33 33 33]
 [33 33 33 33 33 33 33]
 [33 33 33 33 33 33 33]
 [33 33 33 33 33 33 33]
 [33 33 33 33 33 33 33]]


In [ ]:
# create an array with the help of ones with 9 rows and 3 columns

In [38]:
a4 = np.ones((9,3))

In [40]:
print(a4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# create an array with the help of linspace with equal spacing of 2 

In [45]:
a5 = np.linspace(10,30,11)

In [47]:
print(a5)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30.]


In [ ]:
# create an array with the help of arange with step size as 3

In [51]:
a6 = np.arange(0,30,3)

In [53]:
print(a6)

[ 0  3  6  9 12 15 18 21 24 27]


In [ ]:
# create an array with the help of random in which values lie between 10 and 11

In [55]:
a7 = np.random.random(5)+10

In [57]:
print(a7)

[10.82332313 10.66889959 10.79827366 10.12581388 10.06748434]


In [ ]:
# create an array with the help of randomint between 10 and 100

In [93]:
b = []
for i in range(5):
    b.append(np.random.randint(10,100))
a8 = np.array(b)

In [95]:
print(a8)

[11 15 63 97 80]


In [ ]:
# create a 3d array and convert it into 2d and than into 1 d

In [97]:
a9 = np.array([[[4,6,3,2],[1,4,2,5],[1,9,0,7]],[[3,5,6,4],[0,0,3,4],[2,7,7,5]]])
print(a9)
a10 = a9.reshape(4,6)
print(a10)
a11 = a9.reshape(24)
print(a11)

[[[4 6 3 2]
  [1 4 2 5]
  [1 9 0 7]]

 [[3 5 6 4]
  [0 0 3 4]
  [2 7 7 5]]]
[[4 6 3 2 1 4]
 [2 5 1 9 0 7]
 [3 5 6 4 0 0]
 [3 4 2 7 7 5]]
[4 6 3 2 1 4 2 5 1 9 0 7 3 5 6 4 0 0 3 4 2 7 7 5]
