# Data Manipulation

In [ ]:
- It is process of converting the data into a meaningful information that can be 
easily understand or processed as per the requirement 

- collecting the data 
- data manipulation is done with the help of python code 
- organizing the data into proper format


In [ ]:
Problem 
- Duplicates 
- Missing values
- Incorrect format - dd/mm/yy - yy/dd/mm 
- Different units - F --- C , km --- m 
- Unwanted columns - S.No

In [ ]:
# various libraries in python

- NumPy - Array 
- Pandas - Series and DataFrame 
- Matplotlib - Visualization 
- Seaborn - Visualization 
- Scipy - Stats

# NumPy

In [ ]:
- Numerical Python 
- It is n dimensional Array
- Array is a rectangular matrix which consists of rows and columns 
- It is an open source library 
- it is free available 
- It consist of various inbuilt powerfull functions
- It is used for data generation and manipulation 
- We cannot change the index in NumPy 
- it consist of same data type

In [2]:
a = [10,20.5,6+5j, "python", True]
print(a)
print(type(a))

[10, 20.5, (6+5j), 'python', True]
<class 'list'>


In [1]:
import numpy as np 
a = np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
a = np.array([10,20,30.5,40,50])
print(a)
print(type(a))

[10.  20.  30.5 40.  50. ]
<class 'numpy.ndarray'>


In [7]:
a = np.array([10,20,30.5,'40',50])
print(a)
print(type(a))

['10' '20' '30.5' '40' '50']
<class 'numpy.ndarray'>


# Data Generation

In [8]:
a = np.array([0,0,0,0,0])
print(a)

[0 0 0 0 0]


In [9]:
# zeros 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.zeros((5,6))
print(a)
print(type(a))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>


In [10]:
# ones 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6))
print(a)
print(type(a))

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [13]:
# twos 
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6))* 2
print(a)
print(type(a))

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]
<class 'numpy.ndarray'>


In [14]:
# 5 - rows, 6 - column
# by default the data will be in form of float
a = np.ones((5,6)) + 54
print(a)
print(type(a))

[[55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]
 [55. 55. 55. 55. 55. 55.]]
<class 'numpy.ndarray'>


In [15]:
# full 

# 5 - rows, 6 - column, 7 - number
# by default the data will be in form of float
a = np.full((5,6), 7)
print(a)
print(type(a))


[[7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]
 [7 7 7 7 7 7]]
<class 'numpy.ndarray'>


In [16]:
# full 

# 5 - rows, 6 - column, 7.3 - number
# by default the data will be in form of float
a = np.full((5,6), 7.3)
print(a)
print(type(a))

[[7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]
 [7.3 7.3 7.3 7.3 7.3 7.3]]
<class 'numpy.ndarray'>


In [20]:
# linspace - equal spacing 
# 0 - start, 20 - end point , 11 - no of point 
# start and end point are included

a = np.linspace(0,20,10)
print(a)

[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]


In [18]:
a = np.linspace(0,20,25)
print(a)

[ 0.          0.83333333  1.66666667  2.5         3.33333333  4.16666667
  5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.         10.83333333 11.66666667 12.5        13.33333333 14.16666667
 15.         15.83333333 16.66666667 17.5        18.33333333 19.16666667
 20.        ]


In [21]:
# arange 
# 0 - start, 20 - end , 3 - step size 
# end is not included 

a = np.arange(0,20,3)
print(a)

[ 0  3  6  9 12 15 18]


In [22]:
a = np.arange(0,20,5)
print(a)

[ 0  5 10 15]


In [53]:
# random 
# values will always between 0 and 1 
# 1 - random - module 2- random - function
# 40 - no. of points

a = np.random.random(40)
print(a)

[0.83994423 0.07361377 0.58662895 0.37497322 0.50750301 0.51939156
 0.40912895 0.20975055 0.78058934 0.05177169 0.65864237 0.08663848
 0.8854457  0.43296327 0.27553438 0.45213112 0.73803267 0.71741813
 0.9588141  0.20905551 0.31788511 0.4159099  0.36149015 0.48591082
 0.12710001 0.63866005 0.15320391 0.39316563 0.87905755 0.33532975
 0.50999069 0.2213466  0.18511661 0.98364213 0.50568891 0.67039981
 0.97247683 0.09815818 0.31050856 0.47323671]


In [51]:
# randint
# 0 - start, 40 - end 
a = np.random.randint(0,40)
print(a)

3


In [ ]:
# list 
# ones
# zeros 
# full 
# linspace
# arange
# random
# randint

In [55]:
# converting integer into float 

a = np.arange(24, dtype = float)
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]


# Array Inspection

In [61]:
a = np.array(20)
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

20
<class 'numpy.ndarray'>
1
0
()


In [62]:
a = np.array([20,10,30,40,50])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[20 10 30 40 50]
<class 'numpy.ndarray'>
5
1
(5,)


In [63]:
a = np.array([[20,10,30],
              [40,50,60]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[20 10 30]
 [40 50 60]]
<class 'numpy.ndarray'>
6
2
(2, 3)


In [65]:
a = np.array([[20,10,30,50],
              [40,50,60,70],
              [90,80,70,90]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[20 10 30 50]
 [40 50 60 70]
 [90 80 70 90]]
<class 'numpy.ndarray'>
12
2
(3, 4)


In [66]:
a = np.array([[[20,10,30,50],
              [40,50,60,70],
              [90,80,70,90]]])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]]
<class 'numpy.ndarray'>
12
3
(1, 3, 4)


In [67]:
a = np.array([
              [[20,10,30,50],[40,50,60,70],[90,80,70,90]],
              [[20,10,30,50],[40,50,60,70],[90,80,70,90]]
             ])
print(a)
print(type(a))
print(np.size(a)) # count of elements present in the array
print(np.ndim(a)) # dimension of the array
print(np.shape(a)) # will give you the shape of the array

[[[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]

 [[20 10 30 50]
  [40 50 60 70]
  [90 80 70 90]]]
<class 'numpy.ndarray'>
24
3
(2, 3, 4)


# Comparision of Array

In [70]:
# element wise comparision

a = [1,2,3]
b = [1,3,4]
np.equal(a,b)

array([ True, False, False])

In [71]:
a = [1,2,3]
b = [1,2,3]
np.equal(a,b)

array([ True,  True,  True])

In [72]:
# array wise comparision

a = [1,2,3]
b = [1,3,4]
np.array_equal(a,b)

False

In [73]:
a = [1,2,3]
b = [1,2,3]
np.array_equal(a,b)

True

# Array Mathematics

In [78]:
a = [1,2,3,4,5]
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.std(a))

1
5
3.0
3.0
1.4142135623730951


In [79]:
np.sqrt(100)

10.0

In [80]:
np.sin(10)

-0.5440211108893699

In [81]:
np.cos(10)

-0.8390715290764524

In [82]:
np.tan(10)

0.6483608274590867

In [83]:
np.log(10)

2.302585092994046

In [84]:
np.sum([10,20])

30

In [85]:
np.sum([10,20,30,40])

100

In [86]:
np.subtract(10,20)

-10

In [88]:
np.multiply(10,20)

200

In [89]:
np.divide(10,20)

0.5

In [90]:
np.pi

3.141592653589793

In [92]:
a = np.sum([[10,20], [20,50]])
a

100

In [96]:
# column wise summation
a = np.sum([[10,20], 
            [10,50]], axis = 0 )
a

array([20, 70])

In [95]:
# row wise summation
a = np.sum([[10,20], 
            [10,40]], axis = 1 )
a

array([30, 50])

In [102]:
# reshape 

a = np.arange(24)
print(a)
print(np.ndim(a))
print()

b = a.reshape(6,4)
print(b)
print(np.ndim(b))
print()

c = a.reshape(2,3,4)
print(c)
print(np.ndim(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
2

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


# indexing and slicing

In [105]:
# 1d
# indexing
a = np.array([10,20,30,40,50])
print(a)
# 10
a[0]

[10 20 30 40 50]


10

In [106]:
# 30 
a[2]

30

In [107]:
a[4]

50

In [108]:
a[-1]

50

In [110]:
# slicing
a = np.array([10,20,30,40,50])
# [10,20]
# a[start:end+1:step]
a[0:2:1]

array([10, 20])

In [111]:
a = np.array([10,20,30,40,50])
# [30,40]
a[2:4:1]

array([30, 40])

In [112]:
a = np.array([10,20,30,40,50])
# [20,40]
a[1:4:2]

array([20, 40])

In [113]:
# 2d
# indexing
a = np.array([[10,20,30],
              [40,50,60]])

# a[rows,column]
# 10
a[0,0]

10

In [114]:
# 50
a[1,1]

50

In [116]:
# 30
a[0,2]

30

In [117]:
# 3d
# indexing
a = np.array([[[10,20,30],
              [40,50,60],
              [90,80,70]]])

# a[array,rows,column]
# 10 
a[0,0,0]

10

In [118]:
a = np.array([[[10,20,30],
              [40,50,60],
              [90,80,70]]])
# 60
a[0,1,2]

60

In [119]:
# 70
a[0,2,2]

70

In [120]:
# 2d
# slicing
a = np.array([[10,20,30],
              [40,50,60]])

#[[10,20]]

# a[rstart:rend+1:rstep, cstart:cend+1:cstep]
a[0:1:1,0:2:1]



array([[10, 20]])

In [121]:
a = np.array([[10,20,30],
              [40,50,60]])

# [[50,60]]
a[1:2:1,1:3:1]

array([[50, 60]])

In [124]:
# 3d
a = np.array([[[10,20,30],
              [40,50,60]]])
# [[[50,60]]]

a[0:1:1, 1:2:1,1:3:1]

array([[[50, 60]]])

In [ ]:
# handson

In [125]:
# create an array with the help of list having values as float
a_1 = np.array([1.01, 2.8, 88.99, 21.88])
print(a_1)

[ 1.01  2.8  88.99 21.88]


In [126]:
# create an array with the help of zeros with 5 rows and 2 columns 
arr = np.zeros((5, 2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [127]:
# create an array with the help of full with values as 33 
c = np.full([5,2],33)
print(c)

[[33 33]
 [33 33]
 [33 33]
 [33 33]
 [33 33]]


In [128]:
# create an array with the help of ones with 9 rows and 3 columns 
a=np.ones((9,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [129]:
# create an array with the help of linspace with equal spacing of 2 
np.linspace(0,20, 11)


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [130]:
# create an array with the help of arange with step size as 3 
a=np.arange(0,30,3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27]


In [140]:
# create an array with the help of random in which values lie between 10 and 11
a = np.random.random(20) +10
a


array([10.06577869, 10.19261886, 10.70575575, 10.65231139, 10.76590336,
       10.01939801, 10.32629823, 10.03346818, 10.55258991, 10.02878739,
       10.85927444, 10.14666087, 10.78201736, 10.29864769, 10.28240683,
       10.92271146, 10.75673889, 10.22169119, 10.38175865, 10.95458492])

In [132]:
# create an array with the help of random int between 10 and 100
np.random.randint(10, 100)


30

In [138]:
# create a 3d array and convert it into 2d and than into 1 d 
a_3d = np.random.randint(10, 100, size=(2, 3, 4))
print(a_3d)
print()
a_2d = a_3d.reshape((8, 3))
print(a_2d)
print()
a_1d = a_2d.reshape(1, 24)
print(a_1d)

[[[99 69 14 57]
  [80 10 84 34]
  [37 33 52 58]]

 [[98 92 52 33]
  [42 54 48 99]
  [53 47 35 81]]]

[[99 69 14]
 [57 80 10]
 [84 34 37]
 [33 52 58]
 [98 92 52]
 [33 42 54]
 [48 99 53]
 [47 35 81]]

[[99 69 14 57 80 10 84 34 37 33 52 58 98 92 52 33 42 54 48 99 53 47 35 81]]
